### ISSUE TITLE
CREATE_FAILED---ScanAutoScalingGroup

### ISSUE THREAD

**Issue by Sisy** [widdix/aws-s3-virusscan#31] opened 2018-02-21 04:33 UTC
Hi -

Having some issues creating the s3-virusscan stack.

I've followed the instructions you provided as best as possible.

1. Created vpc that you provided (vpc-2azs), which has A/B public subnet. 
2. When creating the s3-virusscan stack, in the wizard I set parentvpc as vpc-2azs.

I'm still seeing this error: 
<img width="1427" alt="error" src="https://user-images.githubusercontent.com/9156361/36623346-bd3b556a-18d1-11e8-9624-2a6d10c9e76d.png">

Thank you

**Comment by icelandman2** [comment] 2018-02-27 05:55
I had the same failure! I wasn't able to resolve, but was able to get a different error by manually setting the scaling bounds to something within reason for my use case.

**Comment by michaelwittig** [comment] 2018-02-27 10:55
There are excellent debug instructions here: https://github.com/widdix/aws-s3-virusscan/issues/12#issue-200617864

**Comment by icelandman2** [comment] 2018-02-28 10:21
I tried again with t2.small (and again with t2.medium) and got:

> 2018-02-28 10:03:35,425 [DEBUG] Using service modifier: /sbin/chkconfig
> 2018-02-28 10:03:35,425 [DEBUG] Setting service clamd.scan to enabled
> 2018-02-28 10:03:35,427 [INFO] enabled service clamd.scan
> 2018-02-28 10:03:35,428 [DEBUG] Restarting clamd.scan due to change detected in dependency
> 2018-02-28 10:03:35,428 [DEBUG] Using service runner: /sbin/service
> 2018-02-28 10:03:45,539 [ERROR] Could not restart service clamd.scan; return code was 1
> 2018-02-28 10:03:45,539 [DEBUG] Service output: Stopping clamd.scan: [FAILED]^M
> Starting clamd.scan: ERROR: LOCAL: Socket file /var/run/clamd.scan/clamd.sock could not be bound: No such file or directory
> [FAILED]^M
> 
> 2018-02-28 10:03:45,540 [ERROR] Error encountered during build of config: Could not restart clamd.scan
> Traceback (most recent call last):
>   File "/usr/lib/python2.7/dist-packages/cfnbootstrap/construction.py", line 542, in run_config
>     CloudFormationCarpenter(config, self._auth_config).build(worklog)
>   File "/usr/lib/python2.7/dist-packages/cfnbootstrap/construction.py", line 270, in build
>     CloudFormationCarpenter._serviceTools[manager]().apply(services, changes)
>   File "/usr/lib/python2.7/dist-packages/cfnbootstrap/service_tools.py", line 161, in apply
>     self._restart_service(service)
>   File "/usr/lib/python2.7/dist-packages/cfnbootstrap/service_tools.py", line 185, in _restart_service
>     raise ToolError("Could not restart %s" % service)
> ToolError: Could not restart clamd.scan
> 2018-02-28 10:03:45,541 [ERROR] -----------------------BUILD FAILED!------------------------
> 2018-02-28 10:03:45,543 [ERROR] Unhandled exception during build: Could not restart clamd.scan
> Traceback (most recent call last):
>   File "/opt/aws/bin/cfn-init", line 171, in <module>
>     worklog.build(metadata, configSets)
>   File "/usr/lib/python2.7/dist-packages/cfnbootstrap/construction.py", line 129, in build
>     Contractor(metadata).build(configSets, self)
>   File "/usr/lib/python2.7/dist-packages/cfnbootstrap/construction.py", line 530, in build
>     self.run_config(config, worklog)
>   File "/usr/lib/python2.7/dist-packages/cfnbootstrap/construction.py", line 542, in run_config
>     CloudFormationCarpenter(config, self._auth_config).build(worklog)
>   File "/usr/lib/python2.7/dist-packages/cfnbootstrap/construction.py", line 270, in build
>     CloudFormationCarpenter._serviceTools[manager]().apply(services, changes)
>   File "/usr/lib/python2.7/dist-packages/cfnbootstrap/service_tools.py", line 161, in apply
>     self._restart_service(service)
>   File "/usr/lib/python2.7/dist-packages/cfnbootstrap/service_tools.py", line 185, in _restart_service
>     raise ToolError("Could not restart %s" % service)
> ToolError: Could not restart clamd.scan
> 2018-02-28 10:03:45,800 [DEBUG] CloudFormation client initialized with endpoint https://cloudformation.us-east-2.amazonaws.com
> 2018-02-28 10:03:45,800 [DEBUG] Signaling resource ScanAutoScalingGroup in stack s3-virusscan with unique ID i-0a26840620b788c49 and status FAILURE

with 

> Feb 28 10:03:35 ip-10-0-1-7 freshclam[2889]: Database updated (6428113 signatures) from database.clamav.net (IP: 72.21.91.8)
> Feb 28 10:03:35 ip-10-0-1-7 clamd[2908]: Received 0 file descriptor(s) from systemd.
> Feb 28 10:03:35 ip-10-0-1-7 clamd[2908]: clamd daemon 0.99.3 (OS: linux-gnu, ARCH: x86_64, CPU: x86_64)
> Feb 28 10:03:35 ip-10-0-1-7 clamd[2908]: Running as user clamscan (UID 497, GID 495)
> Feb 28 10:03:35 ip-10-0-1-7 clamd[2908]: Log file size limited to 1048576 bytes.
> Feb 28 10:03:35 ip-10-0-1-7 clamd[2908]: Reading databases from /var/lib/clamav
> Feb 28 10:03:35 ip-10-0-1-7 clamd[2908]: Not loading PUA signatures.
> Feb 28 10:03:35 ip-10-0-1-7 clamd[2908]: Bytecode: Security mode set to "TrustSigned".
> Feb 28 10:03:44 ip-10-0-1-7 clamd[2908]: Loaded 6422021 signatures.
> Feb 28 10:03:45 ip-10-0-1-7 clamd[2908]: LOCAL: Socket file /var/run/clamd.scan/clamd.sock could not be bound: No such file or directory

from /var/logs/messages. Any idea why the socket isn't found? (Sorry - somewhat new to AWS/not sure if I'm looking at things right)

**Comment by michaelwittig** [comment] 2018-03-08 15:00
Can you attach the template that you are using and the parameters? I try to reproduce the error then.

**Comment by michaelwittig** [comment] 2018-03-19 15:42
duplicate of #32

**Closed by michaelwittig** 2018-03-19 15:42 UTC
Labels: question
