### ISSUE TITLE
Tagging is not working for clean files. 

### ISSUE THREAD

**Issue by ratneswar** [widdix/aws-s3-virusscan#65] opened 2020-07-21 13:26 UTC
AWS Marketplace customers have access to support via email: hello@widdix.net

Hello,

Tagging [clamav-status] is not creating for clean files, I am using below details, it created only for infected test file(s). 

1. DeleteInfectedFiles --- > false
2. TagFiles --- > true

Thanks
Ratneswar

**Comment by michaelwittig** [comment] 2020-07-21 14:05
Any errors in the logs? https://github.com/widdix/aws-s3-virusscan#troubleshooting

**Comment by ratneswar** [comment] 2020-07-22 12:38
Thanks for quick response Michael, I am able to see tags after an hour or so, looks like some latency in tags updates on each object, may be due to the number of objects uploaded to S3, I did around 500 files. 
Is there any flag for enable or disable for ClamAV definition update?

**Comment by michaelwittig** [comment] 2020-07-22 14:25
You can increase `AutoScalingMaxSize` speed up scanning if many objects are enqueued for scanning.

No, you can not disable the definition updates. This also does not seem to be a good idea?

i'm closing this since it's not a bug.

**Closed by michaelwittig** 2020-07-22 14:25 UTC
Labels: question
